<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Page Charset -->
    <meta charset="utf-8">
    <!-- Compatible for IE -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- support responsive page -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title Page -->
    <title>.:: Chapter 2 ::.</title>
    <!-- Include stylesheet library -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
      pre {
        margin-top:20px;
        background-color: rgba(255,0,0,.1);
        border: rgb(255,0,0);
      }
    </style>
  </head>

  <body>
   


   <h2 style="color: black">เพิ่มกิจกรรม</h2>
        <div class="form-group row"> 
          <label class="col-sm-2 col-form-label col-form-label-sm" style="color: black">ชื่อกิจกรรม :</label>
          <div class="col-sm-10">
            <input type="text" id="name" class="form-control" required>
            <div class="valid-feedback" >
              Looks good!
            </div>
            <div class="invalid-feedback">
              Please fill data.
            </div>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm" style="color: black">วันที่ : </label>
          <div class="col-sm-10">
            <input type="date" id="birth" class="form-control">
          </div>
        </div>
    
    
    
    <div class="form-group">
    <label for="exampleFormControlTextarea1" style="color: black">คำอธิบายกิจกรรม :</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
    <!-- Include javascript library -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   
</html>

<script>
  $('#firstName').val('John');
  $('#demo').html('The name of this form is '+$('#firstName').val()+'');

  function insRow(id) {
    let name = $('#name').val();
    let email = $('#email').val();

    if(name == ''){
      $('#name').addClass('is-invalid').removeClass('is-valid').focus();
    }else if(email == ''){
      $('#name').addClass('is-valid').removeClass('is-invalid').focus();
      $('#email').addClass('is-invalid').removeClass('is-valid').focus();
    }else{
      $('#email').addClass('is-valid').removeClass('is-invalid');

      $('#'+ id +' > tbody').append('<tr> \
        <td>'+name+'</td> \
        <td>'+email+'</td> \
      </tr>');
    }
  }
</script>